name: study_app
description: A new Flutter project for studying and managing materials.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  material_symbols_icons: ^4.27.0
  flutter_riverpod: ^2.4.9
  flutter_pdfview: ^1.3.2
  syncfusion_flutter_gauges: ^24.1.41
  shimmer: ^3.0.0
  flutter_svg: ^2.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.svg
    - assets/images/icon.png
